# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import api.grpc.database_pb2 as database__pb2


class DatabaseStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDb = channel.unary_unary(
                '/api.Database/GetDb',
                request_serializer=database__pb2.GetDbRequest.SerializeToString,
                response_deserializer=database__pb2.GetDbResponse.FromString,
                )
        self.InsertDb = channel.unary_unary(
                '/api.Database/InsertDb',
                request_serializer=database__pb2.InsertDbRequest.SerializeToString,
                response_deserializer=database__pb2.InsertDbResponse.FromString,
                )
        self.DeleteDb = channel.unary_unary(
                '/api.Database/DeleteDb',
                request_serializer=database__pb2.DeleteDbRequest.SerializeToString,
                response_deserializer=database__pb2.DeleteDbResponse.FromString,
                )


class DatabaseServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDb(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertDb(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDb(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DatabaseServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDb': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDb,
                    request_deserializer=database__pb2.GetDbRequest.FromString,
                    response_serializer=database__pb2.GetDbResponse.SerializeToString,
            ),
            'InsertDb': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertDb,
                    request_deserializer=database__pb2.InsertDbRequest.FromString,
                    response_serializer=database__pb2.InsertDbResponse.SerializeToString,
            ),
            'DeleteDb': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDb,
                    request_deserializer=database__pb2.DeleteDbRequest.FromString,
                    response_serializer=database__pb2.DeleteDbResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.Database', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Database(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDb(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.Database/GetDb',
            database__pb2.GetDbRequest.SerializeToString,
            database__pb2.GetDbResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InsertDb(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.Database/InsertDb',
            database__pb2.InsertDbRequest.SerializeToString,
            database__pb2.InsertDbResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteDb(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.Database/DeleteDb',
            database__pb2.DeleteDbRequest.SerializeToString,
            database__pb2.DeleteDbResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
