//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: database.proto

package api;

@kotlin.jvm.JvmName("-initializedeleteDbResponse")
inline fun deleteDbResponse(block: api.DeleteDbResponseKt.Dsl.() -> kotlin.Unit): api.DatabaseOuterClass.DeleteDbResponse =
  api.DeleteDbResponseKt.Dsl._create(api.DatabaseOuterClass.DeleteDbResponse.newBuilder()).apply { block() }._build()
object DeleteDbResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: api.DatabaseOuterClass.DeleteDbResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: api.DatabaseOuterClass.DeleteDbResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): api.DatabaseOuterClass.DeleteDbResponse = _builder.build()

    /**
     * <code>uint32 status = 1;</code>
     */
    var status: kotlin.Int
      @JvmName("getStatus")
      get() = _builder.getStatus()
      @JvmName("setStatus")
      set(value) {
        _builder.setStatus(value)
      }
    /**
     * <code>uint32 status = 1;</code>
     */
    fun clearStatus() {
      _builder.clearStatus()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun api.DatabaseOuterClass.DeleteDbResponse.copy(block: api.DeleteDbResponseKt.Dsl.() -> kotlin.Unit): api.DatabaseOuterClass.DeleteDbResponse =
  api.DeleteDbResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

