//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: database.proto

package api;

@kotlin.jvm.JvmName("-initializegetDbResponse")
inline fun getDbResponse(block: api.GetDbResponseKt.Dsl.() -> kotlin.Unit): api.DatabaseOuterClass.GetDbResponse =
  api.GetDbResponseKt.Dsl._create(api.DatabaseOuterClass.GetDbResponse.newBuilder()).apply { block() }._build()
object GetDbResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: api.DatabaseOuterClass.GetDbResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: api.DatabaseOuterClass.GetDbResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): api.DatabaseOuterClass.GetDbResponse = _builder.build()

    /**
     * <code>uint32 status = 1;</code>
     */
    var status: kotlin.Int
      @JvmName("getStatus")
      get() = _builder.getStatus()
      @JvmName("setStatus")
      set(value) {
        _builder.setStatus(value)
      }
    /**
     * <code>uint32 status = 1;</code>
     */
    fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * <code>string data = 2;</code>
     */
    var data: kotlin.String
      @JvmName("getData")
      get() = _builder.getData()
      @JvmName("setData")
      set(value) {
        _builder.setData(value)
      }
    /**
     * <code>string data = 2;</code>
     */
    fun clearData() {
      _builder.clearData()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun api.DatabaseOuterClass.GetDbResponse.copy(block: api.GetDbResponseKt.Dsl.() -> kotlin.Unit): api.DatabaseOuterClass.GetDbResponse =
  api.GetDbResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

