//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: database.proto

package api;

@kotlin.jvm.JvmName("-initializegetDbRequest")
inline fun getDbRequest(block: api.GetDbRequestKt.Dsl.() -> kotlin.Unit): api.DatabaseOuterClass.GetDbRequest =
  api.GetDbRequestKt.Dsl._create(api.DatabaseOuterClass.GetDbRequest.newBuilder()).apply { block() }._build()
object GetDbRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: api.DatabaseOuterClass.GetDbRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: api.DatabaseOuterClass.GetDbRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): api.DatabaseOuterClass.GetDbRequest = _builder.build()

    /**
     * <code>string tb = 1;</code>
     */
    var tb: kotlin.String
      @JvmName("getTb")
      get() = _builder.getTb()
      @JvmName("setTb")
      set(value) {
        _builder.setTb(value)
      }
    /**
     * <code>string tb = 1;</code>
     */
    fun clearTb() {
      _builder.clearTb()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun api.DatabaseOuterClass.GetDbRequest.copy(block: api.GetDbRequestKt.Dsl.() -> kotlin.Unit): api.DatabaseOuterClass.GetDbRequest =
  api.GetDbRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

