//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: database.proto

package api;

@kotlin.jvm.JvmName("-initializeinsertDbResponse")
inline fun insertDbResponse(block: api.InsertDbResponseKt.Dsl.() -> kotlin.Unit): api.DatabaseOuterClass.InsertDbResponse =
  api.InsertDbResponseKt.Dsl._create(api.DatabaseOuterClass.InsertDbResponse.newBuilder()).apply { block() }._build()
object InsertDbResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: api.DatabaseOuterClass.InsertDbResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: api.DatabaseOuterClass.InsertDbResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): api.DatabaseOuterClass.InsertDbResponse = _builder.build()

    /**
     * <code>uint32 status = 1;</code>
     */
    var status: kotlin.Int
      @JvmName("getStatus")
      get() = _builder.getStatus()
      @JvmName("setStatus")
      set(value) {
        _builder.setStatus(value)
      }
    /**
     * <code>uint32 status = 1;</code>
     */
    fun clearStatus() {
      _builder.clearStatus()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun api.DatabaseOuterClass.InsertDbResponse.copy(block: api.InsertDbResponseKt.Dsl.() -> kotlin.Unit): api.DatabaseOuterClass.InsertDbResponse =
  api.InsertDbResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

